name: inventory_barcode_app
description: "Inventory app"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.3
  mobile_scanner: ^5.1.1
  image_picker: ^1.1.2
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
